title = "sis input"

[job]
type = "MD"

[system]
input = "cgpdb"

[files]
      [files.in]
      ffxml = "./rna_cg1.xml"
      cgpdb = "S2HP_random.pdb"

      [files.out]
      dcd = './md.dcd'
      energy = './energy.out'
      restart = './checkpnt.chk'
      out = 'md.out'
      frequency = 1000


[MD]
step = 200000
temperature = 310.15

[basepair]
Uhb_GC = -7.35
Uhb_AU = -4.90
Uhb_GU = -4.90

[electrostatic]
monovalent = -1.0
cutoff = 30.0
