title = "sis input"

[Files]
    [Files.In]
    ff = "./htv23_noBP.ff"
    fasta = "A30.fasta"
    pdb_ini = "A30.pdb"

    [Files.Out]
    prefix = "./md"

[Condition]
tempK = 300.00
rng_seed = 123

[PBC_box]
size = [200.0, 200.0, 200.0]

[MD]
dt_fs = 50.0
nstep = 50000
nstep_save = 500
nstep_save_rst = 500
friction = 0.5

[Electrostatic]
ionic_strength = 0.1
cutoff_type = 1
cutoff = 50.0
no_charge = [1, 27]
length_per_charge = 4.38178046
exclude_covalent_bond_pairs = true

[Progress]
step = 1000

