title = "sis input"

[job]
type = "MDanneal"

[system]
input = "cgpdb"

[files]
      [files.in]
      ffxml = "./rna_cg1.xml"
      cgpdb = "S2HP_random.pdb"
      anneal = "./S2HP_anneal.txt"

      [files.out]
      dcd = './md.dcd'
      energy = './energy.out'
      restart = './checkpnt.chk'
      out = 'md.out'
      frequency = 1000


[MDanneal]
step = 100000

[basepair]
Uhb_GC = -7.35
Uhb_AU = -4.90
Uhb_GU = -4.90

[electrostatic]
monovalent = -1.0
cutoff = 30.0
